### ISSUE TITLE
TypeError: Cannot read property 'createFromPath' of undefined

### ISSUE THREAD

**Issue by Notexe** [MagicCap/MagicCap#185]
I can not open the preferences window at all, I receive this error in the terminal. Using release version 2.0.0b5.
```

TypeError: Cannot read property 'createFromPath' of undefined
    at openConfig (/home/josh/Downloads/magiccap-linux/resources/app/dist/app.js:2:2730)
    at MenuItem.click (/home/josh/Downloads/magiccap-linux/resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/home/josh/Downloads/magiccap-linux/resources/electron.asar/browser/api/menu.js:31:13)
```

**Comment by Notexe** [comment]
**Update:** version 2.0.0b2 seems to work without any issues. The bug only affects v2.0.0b3 and up.

**Comment by Notexe** [comment]
Issue seems to be fixed after this latest commit https://github.com/MagicCap/MagicCap/commit/988430531da4cb72c8e87adf27cbe77cd7dba048
